### ISSUE TITLE
Sourcing "/opt/ros/$ROS_DISTRO/setup.bash" before calling catkin build

### ISSUE THREAD

**Issue by cbschaff** [afdaniele/cpk#3]
In order to find ros packages during catkin build, I needed to source ros' setup.bash before calling catkin build.

To fix this, I edited the catkin build line of the docker file to:

\# build catkin workspace
RUN /bin/bash -c "source /opt/ros/$ROS_DISTRO/setup.bash && catkin build \
    --workspace ${CPK_CODE_DIR}"
 
I'm not sure if this is the solution you want to go with, but it worked in my case.

**Comment by afdaniele** [comment]
This is very specific to ROS, I'd just leave it as is and not have magic things in cpk.
